parameters:
  _param:
    cluster_domain: os_ha_ovs.local
    cluster_name: os_ha_ovs
    infra_config_address: 172.16.10.100
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - cfg01
          - cfg01.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
