classes:
- service.git.client
- system.linux.system.single
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.git
- system.reclass.storage.salt
- system.salt.minion.pki.authority
- system.salt.minion.pki.certificate
- system.sphinx.server.doc.reclass
- system.keystone.client.single
- system.keystone.client.service.nova
- system.mysql.client.single
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_compute_single
- system.reclass.storage.system.openstack_dashboard_single
- system.reclass.storage.system.stacklight_server_cluster
- cluster.mk20_stacklight_advanced
parameters:
  _param:
    reclass_data_repository: "git@github.com:Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: 192.168.10.100
    single_address: 172.16.10.100
    salt_master_host: 127.0.0.1
    salt_master_base_environment: dev
    salt_minion_ca_host: ${linux:network:fqdn}
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: dhcp
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - service.galera.master.cluster
          params:
            mysql_cluster_role: master
        openstack_control_node02:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
        openstack_control_node03:
          classes:
          - service.galera.slave.cluster
          params:
            mysql_cluster_role: slave
