classes:
- cluster.mk22_full_scale
- system.galera.server.cluster
- system.galera.server.database.ceilometer
- system.galera.server.database.cinder
- system.galera.server.database.glance
- system.galera.server.database.heat
- system.galera.server.database.keystone
- system.galera.server.database.nova
- system.linux.system.repo.mos9
parameters:
  _param:
    keepalived_vip_interface: eth1
    keepalived_vip_virtual_router_id: 440
    cluster_vip_address: ${_param:openstack_database_address}
    cluster_local_address: ${_param:single_address}
    cluster_node01_hostname: dbs01
    cluster_node01_address: 172.16.10.181
    cluster_node02_hostname: dbs02
    cluster_node02_address: 172.16.10.182
    cluster_node03_hostname: dbs03
    cluster_node03_address: 172.16.10.183
  linux:
    network:
      interface:
        eth1: ${_param: linux_static_interface}