classes:
- system.linux.system.repo.mos9
- system.linux.system.repo.tcp_extra
- system.galera.server.cluster
- system.galera.server.database.ceilometer
- system.galera.server.database.cinder
- system.galera.server.database.glance
- system.galera.server.database.heat
- system.galera.server.database.keystone
- system.galera.server.database.nova
- cluster.mk22_full_scale
parameters:
  _param:
    keepalived_vip_interface: eth1
    keepalived_vip_virtual_router_id: 80
    cluster_vip_address: ${_param:openstack_database_address}
    cluster_local_address: ${_param:single_address}
    cluster_node01_hostname: dbs01
    cluster_node01_address: ${_param:openstack_database_node01_address}
    cluster_node02_hostname: dbs02
    cluster_node02_address: ${_param:openstack_database_node02_address}
    cluster_node03_hostname: dbs03
    cluster_node03_address: ${_param:openstack_database_node03_address}
  linux:
    network:
      interface:
        eth1: ${_param:linux_static_interface}